- CMakeLists.txt
Build type can be Release, Debug etc.
Currently, it's not possible to build a Debug version of the
library. Let cmake set the appropriate optimization flags;
for MSVC, just add the /EHsc flag to the existing compiler flags.
> Do not ignore cmake build type.

- src/core/common/ojph_arch.h
Hi Aous,
Just a small fix for windows - _BitScanForward calculates trailing zeros directly.
Regards,
Aaron
> ojph_arch: no need to XOR with 31

- src/core/coding/ojph_block_decoder.cpp
- src/core/coding/ojph_block_encoder.cpp
Hi Aous,
Hope all is well. Here are a few small changes to suppress a number of warnings in the 
block encoder/decoder. I've tested the changes in my unit tests and everything seems to work fine.
Regards,
Aaron
> block decoder/encoder: suppress warnings

- .gitignore
- CMakeLists.txt
- Dockerfile
- README.md
- src/apps/common/ojph_img_io.h
- src/apps/ojph_compress/ojph_compress.cpp
- src/apps/ojph_expand/ojph_expand.cpp
- src/apps/others/ojph_img_io.cpp
this adds support for TIF file reading and writing to the ojph_compress and ojph_expand applications respectively.  It uses LIBTIFF for the TIFF reading/writing functionality.
> add tiff-io support to development branch

- src/apps/common/ojph_img_io.h
- src/apps/ojph_compress/ojph_compress.cpp
- src/apps/ojph_expand/ojph_expand.cpp
- src/apps/others/ojph_img_io.cpp
For example, if `in.tif` is a 16 bit TIF file, this will read the top 10 MSBs in the 16bit data and compress it to J2C
`ojph_compress -i in.tif -o out.j2c -bit_depth 10,10,10`
Different bitdepths can be used for each component and also if the bitdepth value is larger than the input TIFs native bitdepth value, then the sample values are left shifted appropriately.  For example
`ojph_compress -i in.tif -o out.j2c -bit_depth 9,17,13`
For example, if `10_12_13.j2c` has component bitdepths 10, 12, 13 then this command will store the decoded samples in the top 10, 12, and 13 MSBs respectively in a 16bit TIF
`ojph_expand -i 10_12_13.j2c -o out.tif`
If a component bitdepth is greater than 16, only the top 16bits of data will be stored in the output TIF file.
> support different bitdepths per component for TIFF IO

- src/core/coding/ojph_block_encoder_avx512.cpp
This is a quick around to the overflow issue.
This WA may cause performance issue
due to high useage of the ZMM register.
> Walk around overflow when block width is bigger than 64

- CMakeLists.txt
- Dockerfile
- src/apps/common/ojph_img_io.h
- src/apps/ojph_compress/ojph_compress.cpp
- src/apps/others/ojph_img_io.cpp
This PR add DPX file read support to ojph_compress
DPX (SMPTE ST268) is a common file format used in the motion picture to store uncompressed 10bit or 16bit RGB data.
Motion Picture film scanners typically output DPX files.  Some workflows also use DPX as a final format for color graded finished video masters.  The most common DPX file variant stores three 10 bit samples (RGB) in a single 32-bit word.
Lossless compression of DPX film scans and video masters is a good application for HTJ2K.
> Feature - dpx file input support for ojph_compress

- src/core/codestream/ojph_params.cpp
- src/core/common/ojph_params.h
The comment (string/data) is not modified, and can be `const`. This makes it easier to pass in something from C++ std::string.
This would be an API change, so OK if you'd prefer to drop it.
> make comment_exchange string const

- src/core/codestream/ojph_codestream.cpp
- src/core/codestream/ojph_codestream_local.cpp
- src/core/codestream/ojph_params_local.h
- src/core/codestream/ojph_tile.cpp
- src/core/common/ojph_codestream.h
This exposes the current tilepart division setting. This avoids needing a shadow variable in the libheif plugin.
Also fixes a couple of typos in the applicable enumeration. I can split that out as a separate PR if preferred.
> add accessors for tilepart division

- src/core/common/ojph_codestream.h
- src/core/common/ojph_params.h
These headers use `OJPH_EXPORT` but do not include the `ojph_arch.h` header that provides it. That potentially causes compile-time errors when using those headers, depending on what other headers are used and the order of inclusion.
> include ojph_arch.h in ojph_codestream.h and ojph_params.h to compensate for OJPH_EXPORT definition

- src/core/codestream/ojph_codestream_local.cpp
> Update ojph_codestream_local.cpp, fix typo

- src/core/codestream/ojph_resolution.cpp
This fixes two bugs in the wavelet transform.
One is when a resolution has one row at a high-pass location.
The other is when a resolution has two rows, the first of which is at a low-pass location; it does not happen when the first row is at a high-pass location.
> Fixing irv97 transform

- src/core/codestream/ojph_resolution.cpp
This fixes a bug when a resolution has one row of 64bit precision.
> Fixes a bug when a resolution has one 64bit line.

- CMakeLists.txt
- src/core/CMakeLists.txt
In order to be exported by cmake (`INSTALL(EXPORT...)`), header directories need to be relative, but they need to be absolute when building.
See example: https://github.com/AcademySoftwareFoundation/openexr/blob/b2b882adb7c0ec1e0eeb235e3ddff6f3657a4f12/cmake/OpenEXRSetup.cmake#L301
Closes https://github.com/aous72/OpenJPH/issues/167
> Allow OpenJPH to be exported by cmake

- src/apps/ojph_compress/ojph_compress.cpp
- src/apps/ojph_expand/ojph_expand.cpp
- src/core/codestream/ojph_codeblock.cpp
- src/core/codestream/ojph_codeblock.h
- src/core/codestream/ojph_codestream_local.cpp
- src/core/codestream/ojph_codestream_local.h
- src/core/codestream/ojph_params.cpp
- src/core/codestream/ojph_params_local.h
- src/core/codestream/ojph_resolution.cpp
- src/core/codestream/ojph_subband.cpp
- src/core/codestream/ojph_tile.cpp
- src/core/codestream/ojph_tile.h
- src/core/codestream/ojph_tile_comp.cpp
- src/core/common/ojph_params.h
- src/core/common/ojph_version.h
This PR modifies the code for QCD and QCC marker segment to support components with differing bit depths/signedness.
For lossy compression, now different components can also have different quantization step sizes.
> Supporting differing components in QCD

- src/core/codestream/ojph_codeblock.cpp
- src/core/codestream/ojph_codeblock.h
- src/core/codestream/ojph_codestream_local.cpp
- src/core/codestream/ojph_codestream_local.h
- src/core/codestream/ojph_params.cpp
- src/core/codestream/ojph_params_local.h
- src/core/codestream/ojph_resolution.cpp
- src/core/codestream/ojph_subband.cpp
- src/core/codestream/ojph_tile.cpp
- src/core/codestream/ojph_tile.h
- src/core/codestream/ojph_tile_comp.cpp
- src/core/common/ojph_params.h
- src/core/common/ojph_version.h
- src/core/transform/ojph_colour_sse2.cpp
This pull requests adds support for COC.
Support for COC allows us to have different coding styles for different components; in particular this can be useful for compressing one component losslessly while employing lossy compression for the others, such as the case for RGBA where we want to employ lossy compression for RGB and compress the alpha channel losslessly.
The applications do not have such support yet.
> This adds support for COC.

- CMakeLists.txt
A follow-up to https://github.com/aous72/OpenJPH/pull/173, see https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#package-version-file
P.S. This is cosmetic, can wait for the next sensible patch release...
> Update CMakeLists.txt for config file naming convention

- src/core/common/ojph_mem.h
```
/home/mark/git/OpenJPH/src/core/common/ojph_mem.h: In member function 'void ojph::mem_fixed_allocator::alloc()':
/home/mark/git/OpenJPH/src/core/common/ojph_mem.h:85:20: warning: deleting 'void*' is undefined [-Wdelete-incomplete]
85 |           delete[] store;
|                    ^~~~~
```
> don't use delete with malloc on store

- src/core/CMakeLists.txt
Fix #196 
Use cmake higher-level abstractions to handle platform differences of -fPIC
```cmake
set_target_properties(openjph PROPERTIES POSITION_INDEPENDENT_CODE ON)
```
Thanks for considering this contribution!I'm looking forward to your feedback and am open to making any necessary changes.
> Handle platform diff of -fPIC

- src/core/codestream/ojph_tile.cpp
Dear library maintainers. I found this bug while working on my work-project, but I do not have any knowledge of how jpeg2000 compression works internally, so this is a "contextual fix". Here my observations and analysis:
I am working with images stored on AWS HealthImaging. AWS is transcoding medical data to jpeg2000 compressed images. AWS also computes CRC32 checksums on the decompressed image data. While working on a data-loader, I noticed that CRC32 sums randomly did not match.
I turned to `valgrind` and analyzed my loader and traced the issue to the line
https://github.com/aous72/OpenJPH/blob/a0ae0ee9f66631d047bd5d81065300f1329b8356/src/core/codestream/ojph_tile.cpp#L421
for which `valgrind` reported that this "conditional jump depends on unitialized data".
By adding some more …
> `nlt_type3[i]` not initialized when `get_nonlinear_transform() == false`
